site_name: TorchRelay
site_url: https://torch-relay.readthedocs.io
repo_url: https://github.com/balbasty/torch-relay
edit_uri: blob/main/docs
site_dir: html
docs_dir: docs
theme:
  name: material
  palette:
    primary: deep orange
    accent: deep orange
  icon:
    repo: fontawesome/brands/github
  logo:
    images/torchrelay_logo_small.svg
plugins:
- mkdocs-jupyter
- mkdocstrings:
    handlers:
      python:
        paths: [..]
        options:
          docstring_style: numpy
          merge_init_into_class: True
          separate_signature: True
          members_order: source
          show_source: False
          show_root_heading: True
markdown_extensions:
- admonition
- toc:
    toc_depth: 2
- markdown_grid_tables
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.arithmatex:
    generic: true
extra_css:
  - stylesheets/extra.css
extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
- Home: index.md
- Installation: install.md
- API:
  - torchrelay: api/index.md
  - torchrelay.extra: api/extra/index.md
  - torchrelay.extra.bounds: api/extra/bounds.md
  - torchrelay.itertools: api/itertools.md
  - torchrelay.multivers: api/multivers/index.md
  - torchrelay.multivers.linalg: api/multivers/linalg.md
  - torchrelay.jit: api/jit.md

watch:
- torchrelay