[build-system]
requires = ["setuptools", "wheel", "versioneer[toml]==0.29"]
build-backend = "setuptools.build_meta"

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "torchrelay/_version.py"
versionfile_build = "torchrelay/_version.py"
tag_prefix = ""
parentdir_prefix = ""